export const LABELS = {
  registry: {
    verra: 'VCS',
    'gold-standard': 'GLD',
    'global-carbon-council': 'GCC',
    'american-carbon-registry': 'ACR',
    'climate-action-reserve': 'CAR',
    'art-trees': 'ART',
  },
  category: {
    agriculture: 'Agriculture',
    forest: 'Forest',
    cookstove: 'Cookstove',
    'ghg-management': 'GHG management',
    'land-use': 'Land use',
    'renewable-energy': 'Renewable energy',
    other: 'Other',
  },
}

export const COLORS = {
  agriculture: 'orange',
  forest: 'green',
  cookstove: 'pink',
  'ghg-management': 'blue',
  'land-use': 'yellow',
  'renewable-energy': 'purple',
  other: 'grey',
}

export const ALL_CATEGORIES = [
  'agriculture',
  'biochar',
  'cookstove',
  'energy-efficiency',
  'forest',
  'fuel-switching',
  'ghg-management',
  'land-use',
  'mine-methane',
  'renewable-energy',
  'transportation',
  'unknown',
]

export const COUNTRIES = [
  'Afghanistan',
  'Albania',
  'Angola',
  'Argentina',
  'Armenia',
  'Aruba',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahamas',
  'Bahrain',
  'Bangladesh',
  'Belize',
  'Benin',
  'Bolivia',
  'Botswana',
  'Brazil',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Cambodia',
  'Cameroon',
  'Canada',
  'Central African Republic',
  'Chad',
  'Chile',
  'China',
  'Colombia',
  'Comoros',
  'Congo Republic',
  'Costa Rica',
  "Cote d'Ivoire",
  'Cyprus',
  'DR Congo',
  'Denmark',
  'Djibouti',
  'Dominican Republic',
  'Ecuador',
  'Egypt',
  'El Salvador',
  'Eritrea',
  'Estonia',
  'Ethiopia',
  'Fiji',
  'France',
  'Gabon',
  'Gambia',
  'Georgia',
  'Germany',
  'Ghana',
  'Greece',
  'Guatemala',
  'Guinea',
  'Guinea-Bissau',
  'Guyana',
  'Haiti',
  'Honduras',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Iraq',
  'Israel',
  'Italy',
  'Japan',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kosovo',
  'Laos',
  'Latvia',
  'Lesotho',
  'Liberia',
  'Lithuania',
  'Madagascar',
  'Malawi',
  'Malaysia',
  'Mali',
  'Mauritania',
  'Mauritius',
  'Mayotte',
  'Mexico',
  'Mongolia',
  'Morocco',
  'Mozambique',
  'Myanmar',
  'Namibia',
  'Nepal',
  'Netherlands',
  'New Caledonia',
  'New Zealand',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'North Macedonia',
  'Oman',
  'Pakistan',
  'Palestine',
  'Panama',
  'Papua New Guinea',
  'Paraguay',
  'Peru',
  'Philippines',
  'Qatar',
  'Romania',
  'Russia',
  'Rwanda',
  'Saudi Arabia',
  'Senegal',
  'Serbia',
  'Sierra Leone',
  'Singapore',
  'Somalia',
  'South Africa',
  'South Korea',
  'Spain',
  'Sri Lanka',
  'Sudan',
  'Suriname',
  'Switzerland',
  'Syria',
  'Taiwan',
  'Tajikistan',
  'Tanzania',
  'Thailand',
  'Timor-Leste',
  'Togo',
  'Tunisia',
  'Turkmenistan',
  'Türkiye',
  'Uganda',
  'Ukraine',
  'United Arab Emirates',
  'United Kingdom',
  'United States',
  'Uruguay',
  'Uzbekistan',
  'Vietnam',
  'Zambia',
  'Zimbabwe',
]
